fastcgi++: Fastcgipp::FcgistreamSink Class Reference
Fastcgipp::FcgistreamSink Class Reference
Encapsulates data into FastCGI records to be sent back to the web server.
#include <fcgistream.hpp>
Public Member Functions
std::streamsize write (const char *s, std::streamsize n)
void set (Protocol::FullId id, Transceiver &transceiver, Protocol::RecordType type)
void dump (const char *data, size_t size)
void dump (std::basic_istream< char > &stream)
Private Attributes
Protocol::FullId m_id
Protocol::RecordType m_type
Transceiver * m_transceiver
Detailed Description
Encapsulates data into FastCGI records to be sent back to the web server.
Definition at line 172 of file fcgistream.hpp.
Member Function Documentation
void Fastcgipp::FcgistreamSink::dump (const char * data, size_t size) inline
Definition at line 182 of file fcgistream.hpp.
References write().
Referenced by Fastcgipp::Fcgistream< charT >::dump().
void Fastcgipp::FcgistreamSink::dump (std::basic_istream< char > & stream)
Definition at line 174 of file fcgistream.cpp.
void Fastcgipp::FcgistreamSink::set (Protocol::FullId id, Transceiver & transceiver, Protocol::RecordType type) inline
Definition at line 181 of file fcgistream.hpp.
References m_id, m_transceiver, and m_type.
Referenced by Fastcgipp::Fcgistream< charT >::set().
std::streamsize Fastcgipp::FcgistreamSink::write (const char * s, std::streamsize n)
Definition at line 137 of file fcgistream.cpp.
References Fastcgipp::Protocol::chunkSize, and Fastcgipp::Protocol::version.
Referenced by dump().
Member Data Documentation
Protocol::FullId Fastcgipp::FcgistreamSink::m_id private
Definition at line 175 of file fcgistream.hpp.
Referenced by set().
Transceiver* Fastcgipp::FcgistreamSink::m_transceiver private
Definition at line 177 of file fcgistream.hpp.
Referenced by set().
Protocol::RecordType Fastcgipp::FcgistreamSink::m_type private
Definition at line 176 of file fcgistream.hpp.
Referenced by set().
The documentation for this class was generated from the following files:
fcgistream.hpp
fcgistream.cpp