fastcgi++: ASql::Data::SetPtrBuilder< T > Class Template Reference
ASql::Data::SetPtrBuilder< T > Class Template Reference
Wraps a Set object around a pointer to a dataset of type T.
#include <data.hpp>
Public Member Functions
SetPtrBuilder ()
Default constructor set's the pointer to null.
SetPtrBuilder (const T &x)
Set the pointer to the address of the object referenced to by x.
SetPtrBuilder (SetPtrBuilder &x)
void set (const T &data)
Set the pointer to the address of the object referenced to by x.
void clear ()
Set the pointer to null.
operator bool () const
Return true if the pointer is not null.
Private Member Functions
virtual size_t numberOfSqlElements () const
Wrapper function for the numberOfSqlElements() function in the data object.
virtual Index getSqlIndex (const size_t index) const
Wrapper function for the getSqlIndex() function in the data object.
Private Attributes
const T * m_data
Pointer to the dataset.
Detailed Description
template<class T>
class ASql::Data::SetPtrBuilder< T >
Wraps a Set object around a pointer to a dataset of type T.
This has the one advantage over SetRefBuilder in that the dataset pointed to can be changed with destroying/rebuilding wrapper object.
Template Parameters:
T object type to point to. Must have numberOfSqlElements() and getSqlIndex() function defined as per the instruction in Data::Set.
Definition at line 410 of file data.hpp.
Constructor & Destructor Documentation
template<class T> ASql::Data::SetPtrBuilder< T >::SetPtrBuilder () inline
Default constructor set's the pointer to null.
Definition at line 422 of file data.hpp.
template<class T> ASql::Data::SetPtrBuilder< T >::SetPtrBuilder (const T & x) inline
Set the pointer to the address of the object referenced to by x.
Definition at line 425 of file data.hpp.
template<class T> ASql::Data::SetPtrBuilder< T >::SetPtrBuilder (SetPtrBuilder< T > & x) inline
Definition at line 427 of file data.hpp.
Member Function Documentation
template<class T> void ASql::Data::SetPtrBuilder< T >::clear () inline
Set the pointer to null.
Definition at line 433 of file data.hpp.
template<class T> virtual Index ASql::Data::SetPtrBuilder< T >::getSqlIndex (const size_t index) const inline private virtual
Wrapper function for the getSqlIndex() function in the data object.
Implements ASql::Data::Set.
Definition at line 419 of file data.hpp.
template<class T> virtual size_t ASql::Data::SetPtrBuilder< T >::numberOfSqlElements () const inline private virtual
Wrapper function for the numberOfSqlElements() function in the data object.
Implements ASql::Data::Set.
Definition at line 416 of file data.hpp.
template<class T> ASql::Data::SetPtrBuilder< T >::operator bool () const inline
Return true if the pointer is not null.
Definition at line 436 of file data.hpp.
template<class T> void ASql::Data::SetPtrBuilder< T >::set (const T & data) inline
Set the pointer to the address of the object referenced to by x.
Definition at line 430 of file data.hpp.
Referenced by ASql::Data::STLSetContainer< T >::manufacture(), ASql::Data::STLSetRefContainer< T >::manufacture(), ASql::Data::STLSharedSetContainer< T >::manufacture(), ASql::Data::STLSetContainer< T >::pull(), ASql::Data::STLSetRefContainer< T >::pull(), and ASql::Data::STLSharedSetContainer< T >::pull().
Member Data Documentation
template<class T> const T* ASql::Data::SetPtrBuilder< T >::m_data private
Pointer to the dataset.
Definition at line 413 of file data.hpp.
Referenced by ASql::Data::SetPtrBuilder< typename T::value_type >::clear(), ASql::Data::SetPtrBuilder< typename T::value_type >::getSqlIndex(), ASql::Data::SetPtrBuilder< typename T::value_type >::numberOfSqlElements(), ASql::Data::SetPtrBuilder< typename T::value_type >::operator bool(), and ASql::Data::SetPtrBuilder< typename T::value_type >::set().
The documentation for this class was generated from the following file:
data.hpp