fastcgi++: ASql::Data::SetContainer Struct Reference
ASql::Data::SetContainer Struct Reference
Base class for containers of Data::Set objects to be used for result/parameter data in SQL queries.
#include <data.hpp>
Public Member Functions
virtual Set & manufacture ()=0
Appends a row to the container and returns a reference to it.
virtual void trim ()=0
Pop a row off the end of the container.
virtual ~SetContainer ()
virtual const Set * pull () const =0
Get a row from the front and move on to the next row.
virtual void init () const =0
Detailed Description
Base class for containers of Data::Set objects to be used for result/parameter data in SQL queries.
Definition at line 531 of file data.hpp.
Constructor & Destructor Documentation
virtual ASql::Data::SetContainer::~SetContainer () inline virtual
Definition at line 537 of file data.hpp.
Member Function Documentation
virtual void ASql::Data::SetContainer::init () const pure virtual
Implemented in ASql::Data::STLSharedSetContainer< T >, ASql::Data::STLSetRefContainer< T >, ASql::Data::IndySTLSetContainer< T >, and ASql::Data::STLSetContainer< T >.
Referenced by ASql::MySQL::Statement::execute().
virtual Set& ASql::Data::SetContainer::manufacture () pure virtual
Appends a row to the container and returns a reference to it.
Implemented in ASql::Data::STLSharedSetContainer< T >, ASql::Data::STLSetRefContainer< T >, ASql::Data::IndySTLSetContainer< T >, and ASql::Data::STLSetContainer< T >.
Referenced by ASql::MySQL::Statement::execute().
virtual const Set* ASql::Data::SetContainer::pull () const pure virtual
Get a row from the front and move on to the next row.
Returns:
This function should return a pointer to the row or null if at the end.
Implemented in ASql::Data::STLSharedSetContainer< T >, ASql::Data::STLSetRefContainer< T >, ASql::Data::IndySTLSetContainer< T >, and ASql::Data::STLSetContainer< T >.
Referenced by ASql::MySQL::Statement::execute().
virtual void ASql::Data::SetContainer::trim () pure virtual
Pop a row off the end of the container.
Implemented in ASql::Data::STLSharedSetContainer< T >, ASql::Data::STLSetRefContainer< T >, ASql::Data::IndySTLSetContainer< T >, and ASql::Data::STLSetContainer< T >.
Referenced by ASql::MySQL::Statement::execute().
The documentation for this struct was generated from the following file:
data.hpp